# Generated by Django 5.0.6 on 2024-06-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_navbar_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='media/')),
                ('button', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='flightfaqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='faqs',
        ),
        migrations.AddField(
            model_name='hotel_cards',
            name='Book_now',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='navbar',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterModelTable(
            name='hotel_cards',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hotel_faqitem',
            table='hotel_faqitem',
        ),
    ]
