# Generated by Django 5.0.6 on 2024-06-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_navbar_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel_faqitem',
            table='hotel_faqitem',
        ),
    ]
